spring:
  application:
    name: config-server
  # ---  Config Server ---
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
         search-locations: file:///etc/config-repo
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
     prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health
