spring:
  mvc:
    throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: user_route
          uri: lb://user-service
          predicates:
          - Path=/api/v1/users/**
        - id: company_rout
          uri: lb://company-service
          predicates:
          - Path=/api/v1/companies/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
      level:
       org.springframework.cloud.gateway: TRACE
       org.springframework.http.client: DEBUG
       reactor.netty.http.client: DEBUG
       org.springframework.cloud.loadbalancer: TRACE
