spring:
  application:
    name: eureka-server

server:
    port: ${EUREKA_SERVER_PORT:8761}
eureka:
      instance:
       hostname: ${EUREKA_INSTANCE_HOSTNAME:eureka-server}
      client:
        register-with-eureka: false
        fetch-registry: false
        serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

