version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:

      POSTGRES_DB_USER: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_cloud_network

  # 2. Config Server
  config-server:
    build: ./config-server
    container_name: config_server_app
    ports:
      - "8888:8888"
    environment:

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres
    networks:
      - my_cloud_network

  # 3. Eureka Server
  eureka-server:
    build: ./eureka-server
    container_name: eureka_server_app
    ports:
      - "8761:8761"
    depends_on:
      - config-server

    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA_SERVER_PORT: 8761
      EUREKA_INSTANCE_HOSTNAME: eureka-server
    networks:
      - my_cloud_network

  # 4. User Service
  user-service:
    build: ./user-service
    container_name: user_service_app
    environment:

      CONFIG_SERVER_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/users_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

    depends_on:
      - postgres
      - config-server
      - eureka-server
    networks:
      - my_cloud_network

  # 5. Company Service
  company-service:
    build: ./company-service
    container_name: company_service_app
    environment:
      CONFIG_SERVER_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/users_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

    depends_on:
      - postgres
      - config-server
      - eureka-server

    networks:
      - my_cloud_network

  # 6. API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api_gateway_app
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SERVER_PORT: 8080
    depends_on:
      - config-server
      - eureka-server

    networks:
      - my_cloud_network


networks:
  my_cloud_network:
    driver: bridge


volumes:
  postgres_data:
    driver: local
